name: schedulify
description: "Multi-tenant college scheduling SaaS"
publish_to: 'none'
version: 0.2.4+3

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.8.4

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Local storage
  shared_preferences: ^2.3.5

  # Calendar
  table_calendar: ^3.2.0

  # HTTP (for Groq API)
  http: ^1.4.0

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  fl_chart: ^0.70.2
  dotted_border: ^2.1.0

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  file_picker: ^8.3.7
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8

  # Attendance system
  geolocator: ^13.0.2
  maps_toolkit: ^3.1.0
  mobile_scanner: ^7.0.0
  qr_flutter: ^4.1.0
  crypto: ^3.0.5
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  firebase_core: ^4.10.0
  firebase_analytics: ^12.4.2
  flutter_svg: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/images/App_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/App_icon.png"
  min_sdk_android: 21
